plugins {
    id 'fml-loom' version '0.1'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "Spongepowered"
        url = "https://repo.spongepowered.org/repository/maven-public/"
    }
    maven {
        name = "ModdedMITE"
        url = "https://maven.limingzxc.top/repository/maven-public/"
    }
}

configurations {
    fml
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "com.google.code.gson:gson:2.11.0"
    implementation "it.unimi.dsi:fastutil:8.5.12"

    fml files('lib/FishModLoader-v3.4.3.jar')
    implementation files('lib/FishModLoader-v3.4.3.jar')
    implementation "com.github.MinecraftIsTooEasy:RustedIronCore:1.5.5"
    compileOnly "com.github.MinecraftIsTooEasy:Waila:2.0.6"

    if (project.hasProperty("withWaila")) {
        runtimeOnly("com.github.MinecraftIsTooEasy:Waila:2.0.6") {
            exclude group: "com.github.MinecraftIsTooEasy", module: "FishModLoader"
            exclude group: "com.github.MinecraftIsTooEasy", module: "RustedIronCore"
            exclude group: "com.github.MinecraftIsTooEasy", module: "Gson"
            exclude group: "com.github.MinecraftIsTooEasy", module: "FastUtil"
        }
    }

}

def fmlResolvedFile = configurations.fml.files.iterator().next()

loom {
    mergedMinecraftJar()
    setFML(fmlResolvedFile)
    dependencies.add("mappings", fmlMCPMappings())
    mods {
        "waystones" {
            sourceSet sourceSets.main
        }
    }
    runs {
        client {
            programArgs "--userProperties", "{}", "--username", project.username,
                    "--session", "a.a.a.a", "--width", project.screen_width,
                    "--height", project.screen_height
        }
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fml.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
    it.options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
    from("LICENSE-MIT") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}
